// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgTOOp1zS2OBIZ--Zf7j3VNK6CgwM1B9Q',
    appId: '1:908253986822:web:cf33f38b0ed7d174074387',
    messagingSenderId: '908253986822',
    projectId: 'todo-e6415',
    authDomain: 'todo-e6415.firebaseapp.com',
    storageBucket: 'todo-e6415.appspot.com',
    measurementId: 'G-32T6WXX4Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdW2HN6TN4p3k40QiUzMiOjF7HbeRWVE',
    appId: '1:908253986822:android:f6785fd27b15f51a074387',
    messagingSenderId: '908253986822',
    projectId: 'todo-e6415',
    storageBucket: 'todo-e6415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NJxUw1nzxQHXgjCewQWhVo2X2nAeAls',
    appId: '1:908253986822:ios:b2febc7ab0f89652074387',
    messagingSenderId: '908253986822',
    projectId: 'todo-e6415',
    storageBucket: 'todo-e6415.appspot.com',
    iosClientId: '908253986822-5914foapmt5rdofi5r07cvoanb2g1kv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson33Firebase01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NJxUw1nzxQHXgjCewQWhVo2X2nAeAls',
    appId: '1:908253986822:ios:9d1865ad8322aa55074387',
    messagingSenderId: '908253986822',
    projectId: 'todo-e6415',
    storageBucket: 'todo-e6415.appspot.com',
    iosClientId: '908253986822-a9di20ktpfnk0m9crl701s04d5vvp933.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson33Firebase01.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgTOOp1zS2OBIZ--Zf7j3VNK6CgwM1B9Q',
    appId: '1:908253986822:web:b002e5b98d710dd2074387',
    messagingSenderId: '908253986822',
    projectId: 'todo-e6415',
    authDomain: 'todo-e6415.firebaseapp.com',
    storageBucket: 'todo-e6415.appspot.com',
    measurementId: 'G-Q7L4LDD4CK',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDgTOOp1zS2OBIZ--Zf7j3VNK6CgwM1B9Q',
    appId: '1:908253986822:web:615b5a9cb38f5b0f074387',
    messagingSenderId: '908253986822',
    projectId: 'todo-e6415',
    authDomain: 'todo-e6415.firebaseapp.com',
    storageBucket: 'todo-e6415.appspot.com',
    measurementId: 'G-K6EH9C4YE7',
  );
}
